queue_rules:
  - name: review
    conditions:
      - status-success=mrmlnc.vscode-scss
      - approved-reviews-by~=mrmlnc|octref

  - name: noreview
    conditions:
      - status-success=mrmlnc.vscode-scss

pull_request_rules:
  - name: Merge with review
    conditions:
      - base=master
      - status-success=mrmlnc.vscode-scss
      - approved-reviews-by~=mrmlnc|octref
      - "label=mergify: merge"
    actions:
      queue:
        method: merge
        name: review

  - name: Merge without review
    conditions:
      - base=master
      - status-success=mrmlnc.vscode-scss
      - "label=mergify: merge"
      - "label=mergify: skip review"
    actions:
      queue:
        method: merge
        name: noreview

  - name: Deleting Merged Branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}
